### ISSUE TITLE
StopIteration in spaghettify_digraph

### ISSUE THREAD

**Issue by stoerr** [emanuelez/PySynergy#6]
I get the following exception when running do_history_conversion.py for two different Synergy repositories:

```
Traceback (most recent call last):
  File "./do_history_conversion.py", line 39, in <module>
    cfe.ccm_fast_export(history, cgraphs)
  File "/home/tmdweb2git/ccm_git_etelco/ccm_fast_export.py", line 121, in ccm_fast_export
    commit_graph = ch.spaghettify_digraph(commit_graph, previous_release, release)
  File "/home/tmdweb2git/ccm_git_etelco/convert_history.py", line 416, in spaghettify_digraph
    current_tails = next((t for t, c in tc.iteritems() if c == component))
StopIteration
```

Obviously it is difficult to post something to reproduce this bug. But perhaps someone can guess the problem, or had the same trouble?

I'm using the latest version of PySynergy with Synergy 7.1. (By the way: for version >= 7.0, one needs to use the classic client, not the web client - took me quite a while to figure out since many synergy exceptions are caught and just logged away somewhere.)

Thanks so much,

Hans-Peter Störr

**Comment by MeMeMax** [comment]
Hi,
i got the same issue. Do you have any hints on resolving the problem?

**Comment by MeMeMax** [comment]
Hi again,
obviously the error is produced by the "for ... in ..." loop. The loop doesn`t find the element in the "tc" set and therefore it quits with "StopIteration".
You find some logging here: http://pastebin.com/snmEnZLR
The third row shows all the content of the hc set and the fourth row shows all the content of the tc set.
In general the hc set has 190 elements while the tc set has only got 184.

Maybe @dvaske could have a clue about this error?

greetings
